name: 'リリースパッケージ作成 (Release Package)'

on:
  push:
    branches:
      - main
    paths:
      - 'manifest.json'
      - 'package.json'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: '共通リリース処理の呼び出し (Invoke Base Release)'
    uses: masanori-satake/common-workflows/.github/workflows/base-release.yml@v1
    permissions:
      contents: write
    with:
      project_name: 'my-chrome-extension'
      build_dir: 'dist'